### ISSUE TITLE
File Trailer

### ISSUE THREAD

**Issue by ghost** [cnaude/PurpleIRC-spigot#10]
How does this feature work, and how can I add this to a channel?

If i put 'latest.log' for the log file will it find spigots log file, or do i need to specify directory structure ie /home/minecraft/logs/latest.log ??

**Comment by cnaude** [comment]
Try something like this in your bot yml file:

``` yaml
file-tailer:
  enabled: true
  file: /home/minecraft/logs/latest.log
  recipient: '#minecraft'
  ctcp: false
```

**Comment by ghost** [comment]
will a `/irc reloadbotconfigs` enable this? or will i need to restart in order for it to hook to the log file?

**Comment by cnaude** [comment]
Yes the reloadbotconfigs will enable it.

**Comment by ghost** [comment]
I tried to use reloadbotconfigs but it did not catch the file. I restarted my server and it is now outputting to the #deltalog channel. However, you might wish to add a delay based on time stamp so that it does not try to send to the channel before the bot has joined causing "cannot send to channel errors" and possible spam 

See: http://hastebin.com/ewaqivuyed.avrasm

**Comment by ghost** [comment]
Also is there formatting in the config.yml for this? It would be nice to add a '[LOGFILE]' prefix to the output

color coding from the log file is also not parsed but thats really not a big deal, however some players in the chan might get a ping.

it perhaps could also be possible to pars out the IRC listerner pool or even setup a LEVEL of report, ie, ERROR, INFO] as a config option to only show those level log file messages.

Is it possible to track more than one log file?

**Comment by cnaude** [comment]
Latest dev build won't send messages to the channel unless already joined. It also includes a new option in for multiple files. In addition a new template called log-tailer is available for use. 

Example of multiple files:

``` yaml
file-tailer:
  enabled: true
  file: /games/spigottest/test1.log
  extra_files:
  - /games/spigottest/test2.log
  - /games/spigottest/test3.log
  recipient: '#giraffe'
  ctcp: true
```
